### ISSUE TITLE
Issue when updating plugin in Craft 3.1

### ISSUE THREAD

**Issue by andrelopez** [enupal/snapshot#12]
Notify

- [x] [1547721436119100001](https://mail.zoho.com/zm/#compose/drafts/1547721436119100001)

**Comment by DynamiteGoesBoom** [comment]
@andrelopez Is there an ETA for this? I'd like to try the plugin out, but it fails to install each time:

![screen shot 2019-01-23 at 2 09 44 pm](https://user-images.githubusercontent.com/39201467/51637280-90c4bf00-1f18-11e9-8ac9-64fb09e10577.png)

**Comment by andrelopez** [comment]
@DynamiteGoesBoom Please click in "Remove it" we're working to add support to Craft 3.1 this week.

**Comment by DynamiteGoesBoom** [comment]
Right, I already did that. Thanks for the quick response.

**Comment by andrelopez** [comment]
@DynamiteGoesBoom We just released Enupal Snapshot v1.2.0 with support for Craft 3.1, please update/install the plugin and let us know if the issue is solved.

**Comment by helleholmsen** [comment]
It doesn't work with version 3.1.12. I tried to delete the plugin and then install again but fails:

```
yii\base\UnknownMethodException: Calling unknown method: enupal\snapshot\services\Snapshots::installDefaultVolume()

Migration: enupal\snapshot\migrations\m190107_000000_add_asset_volume

Output:

Exception: Calling unknown method: enupal\snapshot\services\Snapshots::installDefaultVolume() (/Users/helleholmsen/Sites/rent-idrettslag/vendor/yiisoft/yii2/base/Component.php:300)
#0 /Users/helleholmsen/Sites/rent-idrettslag/vendor/enupal/snapshot/src/migrations/m190107_000000_add_asset_volume.php(18): yii\base\Component->__call('installDefaultV...', Array)
#1 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/db/Migration.php(56): enupal\snapshot\migrations\m190107_000000_add_asset_volume->safeUp()
#2 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(enupal\snapshot\migrations\m190107_000000_add_asset_volume))
#4 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#5 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#6 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /Users/helleholmsen/Sites/rent-idrettslag/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/helleholmsen/Sites/rent-idrettslag/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#11 /Users/helleholmsen/Sites/rent-idrettslag/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#13 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#14 /Users/helleholmsen/Sites/rent-idrettslag/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /Users/helleholmsen/Sites/rent-idrettslag/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /Users/helleholmsen/Sites/rent-idrettslag/public/index.php(21): yii\base\Application->run()
#17 {main}
```

**Comment by andrelopez** [comment]
Hi @helleholmsen 

We just released Enupal Snapshot v1.2.2 with a fix to this error. Could you please update your plugin and let us know if is fixed?

Best,

**Comment by helleholmsen** [comment]
@andrelopez I'm deleting the plugin and trying to install again but it doesn't work. Same errors as above

**Comment by helleholmsen** [comment]
@andrelopez tried again this morning and now it worked. Thank you for the help!

**Comment by andrelopez** [comment]
Thanks for reporting @helleholmsen
