### ISSUE TITLE
Can't generate PDF - BaseSnappy::resolveVolumePathToFolderId() must be of the type string, null given

### ISSUE THREAD

**Issue by johnwbaxter** [enupal/snapshot#39]
### Description

Try and generate a PDF and get the following error.

Here is the stack trace:

2020-10-13 14:15:19 [-][7615][71a77211f5ebc850432519cc7d47ce8f][error][TypeError] TypeError: Argument 2 passed to enupal\snapshot\contracts\BaseSnappy::resolveVolumePathToFolderId() must be of the type string, null given, called in /home/examplecom/vendor/enupal/snapshot/src/contracts/BaseSnappy.php on line 341 and defined in /home/examplecom/vendor/enupal/snapshot/src/contracts/BaseSnappy.php:367
Stack trace:
#0 /home/examplecom/vendor/enupal/snapshot/src/contracts/BaseSnappy.php(341): enupal\snapshot\contracts\BaseSnappy->resolveVolumePathToFolderId('folder:9f9e6989...', NULL)
#1 /home/examplecom/vendor/enupal/snapshot/src/contracts/BaseSnappy.php(301): enupal\snapshot\contracts\BaseSnappy->determineUploadFolderId(Object(enupal\snapshot\contracts\SnappySettings))
#2 /home/examplecom/vendor/enupal/snapshot/src/contracts/SnappyPdf.php(189): enupal\snapshot\contracts\BaseSnappy->getAssetIfFileExists(Object(enupal\snapshot\contracts\SnappySettings))
#3 /home/examplecom/vendor/enupal/snapshot/src/contracts/SnappyPdf.php(65): enupal\snapshot\contracts\SnappyPdf->_generatePdf('\t\t<!DOCTYPE htm...', Object(enupal\snapshot\contracts\SnappySettings))
#4 /home/examplecom/vendor/enupal/snapshot/src/variables/SnapshotVariable.php(41): enupal\snapshot\contracts\SnappyPdf->displayHtml('\t\t<!DOCTYPE htm...', Array)
#5 /home/examplecom/vendor/twig/twig/src/Extension/CoreExtension.php(1499): enupal\snapshot\variables\SnapshotVariable->displayHtml('\t\t<!DOCTYPE htm...', Array)
#6 /home/examplecom/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(enupal\snapshot\variables\SnapshotVariable), 'displayHtml', Array, 'method', false, false)
#7 /home/examplecom/storage/runtime/compiled_templates/c1/c1a07159825eb96497743d89040ce43ce798b3bd6bc851ad1da494b1173202b4.php(804): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(enupal\snapshot\variables\SnapshotVariable), 'displayHtml', Array, 'method')
#8 /home/examplecom/vendor/twig/twig/src/Template.php(184): __TwigTemplate_e4ffcd726ef48b4d0136b6f4c091bcb70c4494fd8add850c1f811fe2dcb6d9f7->block_content(Array, Array)
#9 /home/examplecom/storage/runtime/compiled_templates/62/62c21f9379a52753320a8c701ca44a2a84dc36ef724a560aaf3f99d086fc1768.php(99): Twig\Template->displayBlock('content', Array, Array)
#10 /home/examplecom/vendor/twig/twig/src/Template.php(407): __TwigTemplate_58f3d2e8360fc9a52ca1504f194d4f6614d83ca1561ae73b083e8854545f4946->doDisplay(Array, Array)
#11 /home/examplecom/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /home/examplecom/storage/runtime/compiled_templates/c1/c1a07159825eb96497743d89040ce43ce798b3bd6bc851ad1da494b1173202b4.php(74): Twig\Template->display(Array, Array)
#13 /home/examplecom/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e4ffcd726ef48b4d0136b6f4c091bcb70c4494fd8add850c1f811fe2dcb6d9f7->doDisplay(Array, Array)
#14 /home/examplecom/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /home/examplecom/storage/runtime/compiled_templates/d6/d6df25ef420cf54ef8ebc3350117bb20c51eca9acd100edfdaac05e23a79305d.php(110): Twig\Template->display(Array)
#16 /home/examplecom/vendor/twig/twig/src/Template.php(407): __TwigTemplate_42f1953410eb76bcf9cb2d17fe23a118f5f39a187d736b77ea4b6c3b4b3bf639->doDisplay(Array, Array)
#17 /home/examplecom/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /home/examplecom/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#19 /home/examplecom/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#20 /home/examplecom/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#21 /home/examplecom/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('jobs/_entry', Array)
#22 /home/examplecom/vendor/craftcms/cms/src/web/View.php(436): craft\web\View->renderTemplate('jobs/_entry', Array)
#23 /home/examplecom/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('jobs/_entry', Array, 'site')
#24 /home/examplecom/vendor/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('jobs/_entry', Array)
#25 [internal function]: craft\controllers\TemplatesController->actionRender('jobs/_entry', Array)
#26 /home/examplecom/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /home/examplecom/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /home/examplecom/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#29 /home/examplecom/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#30 /home/examplecom/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#31 /home/examplecom/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 /home/examplecom/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 /home/examplecom/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /home/examplecom/public_html/index.php(21): yii\base\Application->run()

### Steps to reproduce

1. Create PDF
2. See error

### Additional info

- Craft version:3.4.25
- PHP version: 7.2
- Database driver & version: MySql 5.7
- Plugin version:1.2.7

**Comment by johnwbaxter** [comment]
It looks like the plugin settings just needed resaving. Ignore!
